### ISSUE TITLE
Cannot find module 'follow-redirects'

### ISSUE THREAD

**Issue by Oakwine** [nicohman/reimagined-wildbow-scraper#3]
This is my first time here, please correct me if I'm doing something wrong. Thanks for revising the Wildbow scraper. However, I can't get any of the books to scrape, I get the following error instead. I'm trying to run it while in the directory where app.js is located. 

```
module.js:529
    throw err;
    ^

Error: Cannot find module 'follow-redirects'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/mow/Downloads/reimagined-wildbow-scraper-master/reimagined-wildbow-scraper-master/app.js:2:13)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
```
(Also, Worm 2 is now known as Ward, perhaps -r?)

**Comment by Oakwine** [comment]
Nevermind, I see now that 'follow-redirects' is something I'm supposed to install separately.

**Comment by nicohman** [comment]
Yes, running npm install in the main folder should install the needed dependencies. Happy to help!

Edit: I took your suggestion and renamed the -w2 option to -r, and added some clearer installation instructions to the README.

**Comment by nicohman** [comment]
Also, I’ll get on the worm 2 rename if you open a separate issue to remind me when I get home. Thanks for saying that, though!
